### ISSUE TITLE
AOP静态编织

### ISSUE THREAD

**Issue by liuhaoyang** [fs7744/Norns#1]
```
AOP静态编织 分为两条道路：

使用预处理器添加源代码， c#中即 代码生成
（c++等中存在类似宏的处理，可以真正得添加源代码，而c#暂不存在，c# 中对应讨论 https://github.com/dotnet/csharplang/issues/341）。
使用后处理器在编译后的二进制代码上添加指令， dotnet 里面可以叫做 IL 重写。
```

1. 可以使用Roslyn 在编译时修改AST添加拦截的代码
2.使用mono.cecli或者dnlib 在编译后进行IL重写

此外，还有另一种方案。
实现CLR Profiling API 在JIT编译时修改method body。实现真正无任何限制的运行时静态AOP

**Comment by fs7744** [comment]
Hi~ o(*￣▽￣*)ブ

感谢提醒，readme 已经修改

1. 我翻过 msbuild 文档，只找到编译前后的task指定或者完全定制编译，没有找到添加扩展去增强默认编译时
2. 目前正在尝试用mono.cecli 做IL重写，😀
3. CLR Profiling API 好像得用c++做

**Comment by fs7744** [comment]
接下来有空，开始用Roslyn 做下尝试
