### ISSUE TITLE
老铁你去哪里了？

### ISSUE THREAD

**Issue by NMSAzulX** [fs7744/Norns#2]
我的Natasha已经发布了，基于Roslyn，来一起搞啊。

**Comment by Czhang0727** [comment]
大佬确定是我么……


东北亚 · 丧坤 <notifications@github.com>于2019年8月12日 周一上午8:11写道：

**Comment by NMSAzulX** [comment]
@Czhang0727   不是Victor.X.Qu吗.......

**Comment by Czhang0727** [comment]
NOOO ：3

不过natasha是啥：3

东北亚 · 丧坤 <notifications@github.com>于2019年8月12日 周一上午8:14写道：

**Comment by NMSAzulX** [comment]
C#的动态编译库，支持运行时脚本。 https://github.com/dotnetcore/Natasha/
https://github.com/fs7744/Norn 我在这个isssue 下面留言，为啥会弄错人了。。sorry

**Comment by Czhang0727** [comment]
哈哈哈 我前段时间看过这个 向大佬低头

东北亚 · 丧坤 <notifications@github.com>于2019年8月12日 周一上午8:19写道：

**Comment by Czhang0727** [comment]
mark ：D
待会上班摸鱼时候看看


张晨毅 <czhang0727@gmail.com>于2019年8月12日 周一上午8:20写道：

**Comment by NMSAzulX** [comment]
都是大佬，一起低头。 话说fs7744这位老铁去哪里了，还是根本不存在~ 他曾是我库的一位贡献者。

**Comment by Czhang0727** [comment]
不知道……可能在人生的道路上迷路了 ：（

东北亚 · 丧坤 <notifications@github.com>于2019年8月12日 周一上午8:23写道：

**Comment by NMSAzulX** [comment]
: (  大佬们，祝好。

**Comment by Czhang0727** [comment]
我前段时间在写windows更新时候想要个IL 的包……裸写太精污…… 还是向大佬低头

张晨毅 <czhang0727@gmail.com>于2019年8月12日 周一上午8:24写道：

**Comment by NMSAzulX** [comment]
来不及解释了，快上车。首页有专门的微信生态车，油腻大佬，在线教学。

**Comment by Czhang0727** [comment]
BTW 大佬不丢去Nuget 么？

张晨毅 <czhang0727@gmail.com>于2019年8月12日 周一上午8:25写道：

**Comment by Czhang0727** [comment]
卧槽 请给我二维码

东北亚 · 丧坤 <notifications@github.com>于2019年8月12日 周一上午8:28写道：

**Comment by NMSAzulX** [comment]
搜索 DotNetCore.Natasha   这个车很快

**Comment by NMSAzulX** [comment]
![image](https://user-images.githubusercontent.com/16236903/62850656-1c1b6b80-bd16-11e9-9676-5685cdc5a392.png)
